### ISSUE TITLE
What is the license of this lib ?

### ISSUE THREAD

**Issue by RuedigerMoeller** [grofit/knockout.files#3]
You should choose a license type, else anyone using it risks being law sued ..

**Comment by grofit** [comment]
Sorry I never bother with licenses, as I assume you know more about it than me what do I need to do, just provide a license file within the repository?

I couldn't care less about its usage, use it in free, commercial or anything else you fancy.

**Comment by RuedigerMoeller** [comment]
you can put a LICENSE file to the root of your project and paste the apache 2.0 text into it (checkout how other github projects do it). I am also not interested in license stuff, however if I want to use your libs in a project which is itself under e.g. apache, i have to ensure i only use stuff also free (users of my libs requested this ..). Popular licenses for JS are apache2, MIT. I don't know the exact difference though ..

**Comment by grofit** [comment]
Added MIT it seems to be the most free for people to use and do what they want with it.

**Comment by RuedigerMoeller** [comment]
Great :-) Thank you ..Keep up good work !
